### ISSUE TITLE
Need's to be updated

### ISSUE THREAD

**Issue by Kranty69** [kk49/deca_website#29]
It needs to be updated for TheHunter COTWs new update.

**Comment by kk49** [comment]
Updated!

**Comment by thomas1446** [comment]
Sorry but it's always blank for the file  animal_population_8 , [Cuatro Colinas Game Reserve]
(http://mathartbang.com/deca/hp/map.html?r=r8)

**Comment by kk49** [comment]
Did you go I to that reserves and update the wave files? When they change reserves the old save become incompatible with the new reserve until.they silently update you save.

**Comment by thomas1446** [comment]
yes of course, no problem for others reserve

**Comment by thomas1446** [comment]
Sorry it's ok now, (i've taken the old directory)
