### ISSUE TITLE
[Issue] Tool stuck on loading game data, is unusable as of today

### ISSUE THREAD

**Issue by DNLzz99** [kk49/deca_website#41]
When loading the tool the maps are showing, but there's no data appearing on the left hand console. 
On refreshing, the tool seems stuck on "LOADING GAME DATA".
Tried in multiple browsers; Chrome, Brave, Firefox.

This is all the information I can provide. Thanks in advance for fixing.

**Comment by ALVAHO1** [comment]
SAME HERE....

**Comment by MrAndy42** [comment]
Ditto

**Comment by Talwyna** [comment]
bump

**Comment by keviiin-deer** [comment]
same issue here. hoping to fix it, thanks

**Comment by Aaronyalun** [comment]
I have the same problenm,hoping to fix it. thanks

**Comment by kk49** [comment]
Thanks for reporting this! I see the same thing. But when I press one of the reserve buttons it loads properly.

**Comment by DNLzz99** [comment]
> Thanks for reporting this! I see the same thing. But when I press one of the reserve buttons it loads properly.

I can confirm that when you press the reserve buttons the map loads fine and all the POI's and hard coded spawn locations etc. on the right hand side work as before. 

But you used to be able to drag your save files (the numbered folder inside [COTW/Saves]) into the left hand console and view all the different spawn groups inside your save file and see their need zones and routes etc. This is the part that doesn't work anymore.
It used to say 'LOADING GAME DATA' and then jump to the explanation on how to access your save files. When this explanation was displaying you could drag the folder to the console and it would grab it. This does no longer work, instead it stays empty and when you drag the folder to the console it just opens up a new tab with your save file location as the URL.

**Comment by DNLzz99** [comment]
On my end it is working again. I assume you did something ;-) thank you!

If you get to adding/adapting the tool to include the animals mentioned in the other thread that would be amazing.
Thanks for creating and maintaining this tool. I'll remind myself to tip you something

**Comment by MrAndy42** [comment]
Confirmed. Working again for mee too.

Many thanks

**Comment by kk49** [comment]
Yup I fixed it, it takes a while to get through. 

Thanks again for the reports!
