### ISSUE TITLE
[Request] Animals missing in tool, request to add them

### ISSUE THREAD

**Issue by DNLzz99** [kk49/deca_website#42]
Some animals are missing in the tool. 
Others have pointed out that the American Alligator is now missing from Mississippi Acres, and that Te Awaroa is only listing Red Deer in the tool since the last update.

To add to this, the developers backfilled a lot of reserves with new available species. I have added an overview from the patch notes which animals they added to which reserves. When the tool was still working (it's not working now, but yesterday it was) I saw these animals were also not listed on their respective reserves in the tool.

From the patch notes:

Animal Backfilling: Your favorite reserves are getting new residents with the Granite Update. Indeed, we’re backfilling 
previously-released maps with additional animals. Here’s the full list:
Ring Neck Pheasant - Hirschfelden , Cuatro Colinas
Merriam Turkey - Layton Lake
Gray Wolf , Capercaillie - Medved Taiga
Eurasian Wigeon - Vurhonga Savanna
Collared Peccary - Parque Fernando
Canada Goose - Yukon Valley
Mallard - Te Awaroa
Pronghorn - Rancho Del Arroyo
Green Wing Teal - Mississippi Acres

Link to the patch notes: https://store.steampowered.com/news/app/518790/view/3630494404601390364?l=english

I hope this helps. Big thanks for developing this tool.

**Comment by kk49** [comment]
I think these are in now with the latest update.

**Comment by DNLzz99** [comment]
Of course! I still had to visit the reserves with the added animals after the update. Derp derp.
I've tested all of the above mentioned species now and can confirm they all work, except for the Mallard on Te Awaroa.
But that reserve only shows Red Deer and is missing all the other animals (not only Mallard), as mentioned in this thread: https://github.com/kk49/deca_website/issues/40
Also the American Alligator is still missing from Mississippi Acres, as mentioned in this thread: https://github.com/kk49/deca_website/issues/39

Thank you

**Comment by barryb777** [comment]
The "backfill" animals, work for me on the website.

**Comment by kk49** [comment]
Consolidating bugs Alligators and Puma's are missing
